### ISSUE TITLE
PHTTOKENX PHTTX logo 

### ISSUE THREAD

**Issue by PHTTOKENX** [TrustWallet/tokens#1119]
Hi I am wanting to upload my token image so it can be updated on the app. Thank you

My twitter account is twitter.com/phttokenx

My contract address is  0x8a64c0Bd7146710Aa5C2773365Bb620FaF11BEd4

**Comment by PHTTOKENX** [comment]
![0f422f43-e395-464e-845c-421262df87de](https://user-images.githubusercontent.com/47856936/53239681-82430200-3694-11e9-8d09-f44402c236f8.png)

**Comment by kolya182** [comment]
Added here https://github.com/TrustWallet/tokens/commit/331aee761eff056b99edcf2bb9af910bade77972
Also, you can use these graphics to say that your ERC20 token fully compatible with Trust Wallet (https://trustwallet.com/logo-assets). Tokens will show up automatically once the user receives them.
Feel free to share this on social media and tag Trust Wallet:
 Twitter: @trustwalletapp 
Facebook: @trustwalletapp
