### ISSUE TITLE
Update Bankcoin (BCASH ) Logo

### ISSUE THREAD

**Issue by bcashbankcoin** [TrustWallet/tokens#1185]
![0xb5bb48567bfd0bfe9e4b08ef8b7f91556cc2a112](https://user-images.githubusercontent.com/46301303/53698123-b770f200-3e02-11e9-9f2e-24ff22a2f320.png)
Token : Bankcoin 
Symbol : BCASH
Decimal : 18
Contract : 0xb5BB48567BfD0bFE9e4B08EF8b7f91556CC2a112
Logo : https://bankcoinbcash.com/bcash.png
Update BCASH Logo on Trust Wallet

**Comment by kolya182** [comment]
Added here https://github.com/TrustWallet/tokens/commit/b4e8efd8ac18bdcab495849f74be8814c8a3a6cf
Also, you can use these graphics to say that your ERC20 token fully compatible with Trust Wallet (https://trustwallet.com/logo-assets). Tokens will show up automatically once the user receives them.
Feel free to share this on social media and tag Trust Wallet:
 Twitter: @trustwalletapp 
Facebook: @trustwalletapp
