### ISSUE TITLE
Upload MBCASH Logo

### ISSUE THREAD

**Issue by mbcashme** [TrustWallet/tokens#1191]
![0xefbb3f1058fd8e0c9d7204f532e17d7572affc3e](https://user-images.githubusercontent.com/41523975/53791786-6a9d3080-3f54-11e9-84be-f34823520339.png)
Token : MBCash
Symbol : MBCAH
Contract :0xEfbB3F1058fd8E0C9d7204f532E17d7572AFfc3e 
Logo : https://mbcash.me/mbcash.png
Logo Update

**Comment by kolya182** [comment]
Addede
Also, you can use these graphics to say that your ERC20 token fully compatible with Trust Wallet (https://trustwallet.com/logo-assets). Tokens will show up automatically once the user receives them.
Feel free to share this on social media and tag Trust Wallet:
 Twitter: @trustwalletapp 
Facebook: @trustwalletapp
