### ISSUE TITLE
Bitcoin Card (VD) Token Logo Update

### ISSUE THREAD

**Issue by bitcoincardvd** [TrustWallet/tokens#1192]
![0x9a9bb9b4b11bf8eccff84b58a6ccccd4058a7f0d](https://user-images.githubusercontent.com/42966723/53792040-fb740c00-3f54-11e9-96d9-786a225f9061.png)
Token : Bitcoin Card
Symbol : VD
Contract :0x9a9bB9b4b11BF8eccff84B58a6CCCCD4058A7f0D 
Logo Link : https://bitcoincard.me/vd.png
Logo Update

**Comment by kolya182** [comment]
Addede
Also, you can use these graphics to say that your ERC20 token fully compatible with Trust Wallet (https://trustwallet.com/logo-assets). Tokens will show up automatically once the user receives them.
Feel free to share this on social media and tag Trust Wallet:
 Twitter: @trustwalletapp 
Facebook: @trustwalletapp
