### ISSUE TITLE
Bankcoin Cash (BKC) Logo Upload

### ISSUE THREAD

**Issue by bankcoincash** [TrustWallet/tokens#1193]
![0xc88be04c809856b75e3dfe19eb4dcf0a3b15317a](https://user-images.githubusercontent.com/38536012/53792196-4b52d300-3f55-11e9-9655-86a9c349ceef.png)
Token : Bankcoin Cash
Symbol : BKC
Contract :0xc88Be04c809856B75E3DfE19eB4dCf0a3B15317a 
Logo Link : https://bankcoin-cash.com/bankcoincash.png
Logo Update

**Comment by kolya182** [comment]
Addede
Also, you can use these graphics to say that your ERC20 token fully compatible with Trust Wallet (https://trustwallet.com/logo-assets). Tokens will show up automatically once the user receives them.
Feel free to share this on social media and tag Trust Wallet:
 Twitter: @trustwalletapp 
Facebook: @trustwalletapp
