### ISSUE TITLE
0x611c74310a06B10593E073aFFe4Ea543b793f539.png

### ISSUE THREAD

**Issue by fincrypchain-io** [TrustWallet/tokens#1259]
![logo](https://user-images.githubusercontent.com/48567830/54401514-ef314100-4702-11e9-80ad-661e4f389ab0.png)

FINCRYPCHAIN  ( FCC )

https://img1.wsimg.com/blobby/go/d3484d1b-eef9-4528-8dac-faf31fe0acac/downloads/LOGO%20FCC.png?ver=1552632844684

0x611c74310a06B10593E073aFFe4Ea543b793f539.png

**Comment by BIGCRYPTO001** [comment]
Hello sir

**Comment by BIGCRYPTO001** [comment]
Hoe about FCC

**Comment by kolya182** [comment]
Image for this token already exists

**Comment by BIGCRYPTO001** [comment]
Thanks sir
