### ISSUE TITLE
CET token logo is not right

### ISSUE THREAD

**Issue by bibodeng** [TrustWallet/tokens#1392]
We found that CET token logo is not right, the logo is belong to CoinEx Token, but with an address of **Dicet** for name.

please check **tokens/0xf660ca1e228e7be1fa8b4f5583145e31147fb577.png**

**Comment by kolya182** [comment]
Updated here https://github.com/TrustWallet/tokens/commit/7b1ece53b42a276193cc1f08cb26fc517588cfb3
