### ISSUE TITLE
Add Euphoria token logo

### ISSUE THREAD

**Issue by EuphoriaStore** [TrustWallet/tokens#1403]
Name Token : Euphoria
![euphoria transparent 2-1](https://user-images.githubusercontent.com/38180589/55623056-1fb84800-57a2-11e9-86a0-121d33938e18.png)

Symbol : EPH
Decimal : 8
Contract Address : 0x875089a734213ca39f0d93c2bbb8209827ec5e9f

**Comment by kolya182** [comment]
Added here https://github.com/TrustWallet/tokens/commit/2c48e449b98eb8de8a8c5be9f4ce789ffea46d2e. But, please follow official guidelines next time
