### ISSUE TITLE
Missing license 

### ISSUE THREAD

**Issue by ligi** [TrustWallet/tokens#146]
This repository should have a license

**Comment by vikmeup** [comment]
@ligi what license would you suggest?

**Comment by ligi** [comment]
I am using MIT for ethereum-lists - but perhaps a CC - e.g. CC0 would be better. IANAL - but no license is really bad - think any license is better than none ;-)

**Comment by vikmeup** [comment]
Fix: https://github.com/TrustWallet/tokens/commit/9389156b8c4d4bc398a7f06bf77ece8495d2adb3
