### ISSUE TITLE
Image updated (however not updated)

### ISSUE THREAD

**Issue by bitstashco** [TrustWallet/tokens#1462]
I recently did a pull request however it did not update the token?

Image updated

_Originally posted by @kolya182 in https://github.com/TrustWallet/tokens/pull/1443#issuecomment-481504143_

**Comment by kolya182** [comment]
It's because of cache on your phone, wait for couple of days to get image updated for new users new logo will be displayed
![2019-04-11 12 52 02](https://user-images.githubusercontent.com/3277207/55988399-a49ada00-5c58-11e9-804f-e04bc37d02ed.jpg)
