### ISSUE TITLE
Add script adding BEP2 tokens images

### ISSUE THREAD

**Issue by kolya182** [TrustWallet/tokens#1725]
https://explorer.binance.org/api/v1/assets?page=1&rows=15

**Comment by daddyfatstacksBIG** [comment]
#1789

**Comment by cashaadev** [comment]
where i need to add BEP2 image in coin or BEP2 Folder?

**Comment by kolya182** [comment]
@cashaadev At the moment all tokens goes in `/tokens` folder, start from reading readme file for this repo. We also have experimental  [BEP2](https://github.com/TrustWallet/tokens/tree/master/BEP2), you can also upload there. I have modified your PR https://github.com/TrustWallet/tokens/commit/a5044c2eb680480b15b571e1b4d62d5313bba55c to fit requirements.

**Comment by cashaadev** [comment]
thanks. cashaa logo will be reflected in trust wallet ?.
