### ISSUE TITLE
Bitcarecoin

### ISSUE THREAD

**Issue by bitcarecoin** [TrustWallet/tokens#1768]
Tried adding 9911.png image for Bitcarecoin. 

Contract :0x511798118e18f0c51acabf138427d6caadeccc76.png

Just wanting to add coin to trustwallet and add image 
--

![9911](https://user-images.githubusercontent.com/51423900/59006598-ae176d00-87d7-11e9-8a40-0643f1b64be9.png)

**Comment by kolya182** [comment]
https://github.com/TrustWallet/tokens/commit/6d975fff7ced0e6611a2d82bffdf8ac800a188a4

**Comment by bitcarecoin** [comment]
You’re awesome.

Thank you

Sent from my iPhone

On Jun 6, 2019, at 12:24 AM, Mykola <notifications@github.com<mailto:notifications@github.com>> wrote:


6d975ff<https://github.com/TrustWallet/tokens/commit/6d975fff7ced0e6611a2d82bffdf8ac800a188a4>
