### ISSUE TITLE
Upload Logo Hitfinex (HFX)

### ISSUE THREAD

**Issue by cryptonana** [TrustWallet/tokens#1779]
Token : Hitfinex
Symbol : HFX
Contract :0x7024e48b4b6439307920eb1d71682fe18262189c
Logo : https://hitfinex.com/0x7024e48b4b6439307920eb1d71682fe18262189c.png

**Comment by kolya182** [comment]
Make sure to follow upload guidelines next time https://developer.trustwallet.com/add_new_token_image
For now added here https://github.com/TrustWallet/tokens/commit/347ea0d20443080bf0fdd26fbb1eb3112cff2254
