### ISSUE TITLE
Add BOK logo

### ISSUE THREAD

**Issue by rwander7** [TrustWallet/tokens#1831]
![0x27c743954bce1bfaef8bcbd685527531001d88d7](https://user-images.githubusercontent.com/51877870/59565137-1b3cc500-9058-11e9-9784-b751da65c5d1.png)

**Comment by kolya182** [comment]
@rwander7 What is the contract address for this token ?

**Comment by rwander7** [comment]
0x27c743954bce1bfaef8bcbd685527531001d88d7

**Comment by kolya182** [comment]
Added here https://github.com/TrustWallet/tokens/commit/95b66be92880235eb99d0de3a5ca89d216378a84
