### ISSUE TITLE
Update BOOM (BOOM) logo

### ISSUE THREAD

**Issue by BoomToken** [TrustWallet/tokens#1938]
Contract address: 0x973b569b1d025C41cD9c19cbf8f931175e874DD0

![BOOM LOGO](https://user-images.githubusercontent.com/52421965/60461498-a2845e00-9c3e-11e9-9ff0-2a65b3152476.png)

**Comment by kolya182** [comment]
Added here https://github.com/TrustWallet/tokens/commit/3222ccd241b74be8a78b86a954775b9dc5418c3e
