### ISSUE TITLE
Icon doesn't change after pull request

### ISSUE THREAD

**Issue by russeltixguru** [TrustWallet/tokens#194]
Hi i want to ask the problem about the icon didn't update in the app after merging pull request. Image name is 0xa843343b1658dea67e83cbd11da0b73728a1b185.png . (TixguruToken TIX)

Old icon is:
 
![34637623_1987010914642420_3065613158983925760_n](https://user-images.githubusercontent.com/37525100/40954311-99be9518-68b6-11e8-9274-3b303fc796d6.jpg)

New icon is:

![0xa843343b1658dea67e83cbd11da0b73728a1b185](https://user-images.githubusercontent.com/37525100/40954317-a8a1cdfc-68b6-11e8-8143-61d8d47d4233.png)

Thanks !

**Comment by vikmeup** [comment]
We have local cache for a week on your phone. It will be new for the new people, or wait for a week on your side.
