### ISSUE TITLE
0x4B32CA05509ca4ffDBb7D2D82B27bc48Ecde62F2

### ISSUE THREAD

**Issue by Kingnuze** [TrustWallet/tokens#3]
![-1](https://user-images.githubusercontent.com/36174335/35834240-b135d2e4-0acc-11e8-8568-5cb0ff4a6435.png)

**Comment by michaelScoff** [comment]
@Kingnuze you need to create a pull request for this. Go to this page: https://github.com/TrustWallet/tokens/tree/master/images press on upload image and add an image, make sure your name in lower case, please details in the readme.

**Comment by Kingnuze** [comment]
can you grant me push access to upload the image..
