### ISSUE TITLE
Uploading token image issue

### ISSUE THREAD

**Issue by visualfodder** [TrustWallet/tokens#691]
Hi,

I've been trying to add our token image but cannot as uploads are disabled.

Can you advise how I can upload please?

Thanks

![0xa5e83c9a22fa75ba20aeba4a4e734c91e8f1d356](https://user-images.githubusercontent.com/43266800/47868728-e64b6d00-ddfc-11e8-8904-44fbd56b068b.png)

**Comment by kolya182** [comment]
Added here https://github.com/TrustWallet/tokens/commit/13a29484034fd0391c4f98c6876e753a899b7784, you uploaded to wrong directory

**Comment by visualfodder** [comment]
Thank you kindly Sir :)
