### ISSUE TITLE
Support icons for Tron tokens

### ISSUE THREAD

**Issue by kolya182** [trustwallet/tokens#740]

**Comment by vikmeup** [comment]
This might be helpful: https://tronscan.org/#/tokens/list

**Comment by ashrafaltayeb** [comment]
> _No description provided._

HELLO MY FRIEND ,  i cant get my trust wallet ERC20 icon update , can you help me

**Comment by chetlahet001** [comment]
🖍️trustwallet

**Comment by chetlahet001** [comment]
Issue

**Comment by chetlahet001** [comment]
issue
