### ISSUE TITLE
Add logo for DONUT token

### ISSUE THREAD

**Issue by haydenadams** [TrustWallet/tokens#981]
DONUT is a popular new token that allows trading of reddit karma. It is currently listed on:

Uniswap: https://twitter.com/UniswapExchange/status/1087366193181265925
Airswap: https://twitter.com/airswap/status/1088188935732383745
Boxswap: https://twitter.com/boxswapio/status/1087959477385601029
Switcheo: https://medium.com/switcheo/switcheo-lists-donut-donut-e6fd385460b

and I believe 0x, and forkdelta as well. On Uniswap, it traded over $10,000 in volume today. It would be great if you added the icon to your library (which is currently being used by Uniswap).  Here is a 256x256 png that is being used as the logo:

![0x23d80c4ee8fb55d4183dd9329296e176dc7464e1](https://user-images.githubusercontent.com/9343483/51645232-4a378a80-1f41-11e9-980a-42e15bb4aa26.png)

**Comment by vikmeup** [comment]
@haydenadams can you follow this guide to add it: https://github.com/TrustWallet/tokens#requirements ? happy to support it.

**Comment by kolya182** [comment]
Added here https://github.com/TrustWallet/tokens/commit/11a809cbf1230868b176986b84319cdc7d8dfe5c
