### ISSUE TITLE
Token verification API throwing error

### ISSUE THREAD

**Issue by FaysalM** [TrustWallet/tokens#989]
Hi All

Going through your travis logs, looks like your token verification API returns nothing.
https://api.trustwallet.com/tokens/verification

Log from Travis
0.57s$ npm test
> tokens@1.0.0 test /home/travis/build/TrustWallet/tokens
> npm run pre-test && node ./test/index.js
> tokens@1.0.0 pre-test /home/travis/build/TrustWallet/tokens
> find . -name '.DS_Store' -type f -delete
Passed all tests
Failed to verify tokens "value" required in setHeader("TOKEN_VERIFICATION_KEY", value)
npm ERR! Test failed.  See above for more details.
The command "npm test" exited with 1.
cache.2
store build cache
0.00s1.21snothing changed, not updating cache
Done. Your build exited with 1.

**Comment by FaysalM** [comment]
Here are the headers returned when verifying the API 
Basically getting a 404

access-control-allow-origin →*
cf-ray →49e2ddf93d6822f4-LAX
content-encoding →br
content-security-policy →default-src 'self'
content-type →text/html; charset=utf-8
date →Thu, 24 Jan 2019 13:32:37 GMT
expect-ct →max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"
server →cloudflare
status →404
via →1.1 vegur
x-content-type-options →nosniff
x-powered-by →Express

**Comment by FaysalM** [comment]
#988  Adding pull request reference

**Comment by kolya182** [comment]
Will investigate this
